### ISSUE TITLE
[Unified Portal] Show logs

### ISSUE THREAD

**Issue by GUSAR1T0** [GUSAR1T0/VXDS-DEV-TOOLS#44]
### Description

Create page for logs view in **read-only** mode and add a possibility to do some actions with logs table.

### Sub-tasks

- [x] Divide `Operations` and `Logs`
- [x] Create view with table;
- [x] Add filters (types of working process, types of message, dates, operations);
- [x] Implement pagination mechanism.
