### ISSUE TITLE
[Unified Portal] Dashboard: statistics and charts

### ISSUE THREAD

**Issue by GUSAR1T0** [GUSAR1T0/VXDS-DEV-TOOLS#64]
### Description

Update home page (dashboard): add statistics and charts.

### Categories

User Profile:
- [x] User Profile
- [x] Mini-cards

Users:
- [x] Users
- [x] User Roles

Components:
- [x] Projects
- [x] ~Modules~ (will be available after implementation of #63 issue)

System:
- [x] Operations
- [x] Logs

**Comment by GUSAR1T0** [comment]
Add 4 mini-card (user and server specific):
- [x] Notifications (the functionality is not implemented, see #67)
- [x] Incidents (the functionality is not implemented, see #66)
- [x] Server Date / Time
- [x] Health check
